
"""
Config
"""

SIDEBAR = {
    "name": "Semantic Defense Reasoner",
    "caption": "An Ontology-Driven Expert System for MITRE D3FEND Enrichment",
    "help":"This semantic expert system maps raw alert Wazuh to the MITRE D3FEND framework. By extracting localized knowledge graphs and applying Description Logic (DL) reasoning, it infers implicit defensive mechanisms to provide traceable explainability for SOC analysts."
}

PIPELINE = {
    "1": {
        "name": "Wazuh Alert Ingestion",
        "caption": "Raw JSON Parsing & Syntactic RDF Translation",
        "help": "In this stage, the user inputs a raw security alert generated by Wazuh. The system parses the JSON payload to extract key observables and translates them into a foundational, unannotated RDF graph. This structural conversion prepares the data for formal semantic binding in the next stage.",
        "steps": {
            "1.1": {
                "name": "Load Wazuh alert (JSON)",
                "file": "tag_1_1_parsed_wazuh_alert.json",
                "type": "json",
                "help":  "Carregue ...",
                "template": "data/templates/alert_fields_to_parse.json"
            },
            "1.2": {
                "name": "Convert parsed alert to RDF",
                "file": "tag_1_2_parsed_wazuh_alert_as_rdf.rdf",
                "type": "rdf",
                "help": "Extrai ...",
                "template": "data/templates/parsed_fields_to_unannotated_rdf.json"
            }
        }
    },

    "2": {
        "name": "Modular Knowledge Base Assembly",
        "caption": "Load and parse Wazuh alert data",
        "help": "The methodology of extracting specific structural modules from a reference ontology and combining them with instantiated alert data to build a specific Knowledge Base.",
        "steps": {
            "2.1": {
                "name": "TBox File Resource Verification",
                "file": "tag_2_1_d3fend.owl",
                "type": "owl",
                "help": "A check to validate the existence, accessibility, and structural integrity of the static reference ontology (MITRE D3FEND) file.",
                "template": ""
            },
            "2.2": {
                "name": "Alert Semantic Annotation",
                "file": "tag_2_2_rdf_wazuh_alert_with_semantic_annotation.owl",
                "type": "owl",
                "help": "The standalone process of transforming raw security alert data into structured RDF assertions (ABox), utilizing predefined domain namespaces to ensure ontological compatibility.",
                "template": "data/templates/unannotated_rdf_to_semantically_annotated_rdf.json"
            },
            "2.3": {
                "name": "ABox (alert) Instantiation to TBox (D3FEND)",
                "file": "tag_2_3_full_knowledge_graph.owl",
                "type": "owl",
                "help": "The integration phase where the standalone ABox assertions (the alert event) are logically bound to the TBox, followed by the serialization of the unified graph into a formal .owl file",
                "template": ""
            },
            "2.4": {
                "name": "Create modular Knowledge Base (Subgraph Extraction)",
                "file": "tag_2_4_modular_knowledge_graph.owl",
                "type": "owl",
                "help": "An algorithmic filtering layer that processes the unified, unreasoned knowledge base to extract a localized semantic subgraph based on predefined configuration parameters.",
                "template": "data/templates/modular_knowledge_graph_methods.json"
            }
        }
    },

    "3": {
        "name": "Deductive Semantic Inference",
        "caption": "Validate and materialize the semantic knowledge base using Description Logic reasoning",
        "help": "The computational core of the expert system. This stage applies a Description Logic reasoner to check the logical consistency of the assembled knowledge base and, if valid, compute its deductive closure by materializing implicit semantic assertions.",
        "steps": {
            "3.1": {
                "name": "Logical Consistency Checking",
                "file": "tag_3_1_dl_consistent_kb.owl",
                "type": "owl",
                "help": "Runs the Pellet DL reasoner over the knowledge base generated to verify whether the ontology is logically consistent. If no inconsistency is detected, this step stores a copy of the knowledge base as the validated consistent KB.",
                "template": ""
            },
            "3.2": {
                "name": "Semantic Assertion Materialization",
                "file": "tag_3_2_materialized_kb.owl",
                "type": "owl",
                "help": "Runs the Pellet DL reasoner over the consistent knowledge base from Step 3.1 and saves the materialized ontology, including implicit class memberships and object property assertions inferred from the ontology axioms.",
                "template": ""
            }
        }
    },

    "4": {
            "name": "Competency Question-Based Explainability",
            "caption": "Resolve predefined competency questions over the materialized knowledge base.",
            "help": "The explanatory layer of the expert system, dedicated to answering predefined competency questions over the materialized knowledge base and transforming the results into traceable defensive explanations and recommendations.",
            "steps": {
                "4.1": {
                    "name": "Competency Question Resolution",
                    "file": "tag_4_1_competency_question_results.json",
                    "type": "json",
                    "help": "Executes predefined SPARQL competency questions against the materialized knowledge base to retrieve alert context, semantic associations, reasoning paths, and candidate defensive artifacts.",
                    "template": "data/templates/competency_questions_template.json"
                },
                "4.2": {
                    "name": "Defensive Advisory Synthesis",
                    "file": "tag_4_2_defensive_advisory.md",
                    "type": "md",
                    "help": "Transforms the competency question results into a structured defensive advisory, combining explanation, reasoning trace, supporting evidence, and recommended defensive actions.",
                    "template": "data/templates/defensive_advisory_template.json"
                },
                "4.3": {
                    "name": "Reasoning Path Visualization",
                    "file": "tag_4_3_reasoning_path_graph.mmd",
                    "type": "mmd",
                    "help": "Transforms selected competency question results into a directed Mermaid graph showing the path from alert evidence to semantic interpretation and defensive recommendation.",
                    "template": ""
                }
            }
        }
}